import React from 'react'
import { FaDribbbleSquare, FaFacebookSquare, FaGithubSquare, FaTwitterSquare, FaInstagramSquare } from 'react-icons/fa'

export const Footer = () => {
    return (
        <div className='max-w-[1240px] text-gray-300 py-2'>
            <div className=' w-full mx-auto px-4 py-16 grid lg:grid-cols-3 gap-8 '>
                <div>
                    <h1 className='text-[#00df9a] font-bold text-2xl w-full '>DataS.</h1>
                    <p className='py-2 capitalize md:text-lg'> collect and perform Multilevel Analyses on the data generated by the brands.</p>
                    <div className='flex flex-row justify-between items-center my-2 md:w-[75%] mx-auto  '>
                        <FaDribbbleSquare size={30} />
                        <FaFacebookSquare size={30} />
                        <FaGithubSquare size={30} />
                        <FaTwitterSquare size={30} />
                        <FaInstagramSquare size={30} />
                    </div>
                </div>
                <div className='lg:col-span-2 flex justify-between mt-8'>
                    <div>
                        <h5 className='font-medium text-gray-400 mb-2 capitalize'>Solutions</h5>
                        <ul >
                            <li className='capitalize py-2 text-sm  ' >analytics</li>
                            <li className='capitalize py-2 text-sm  ' >marketing</li>
                            <li className='capitalize py-2 text-sm  ' >commerce</li>
                            <li className='capitalize py-2 text-sm  ' >insights</li>
                        </ul>
                    </div>
                    <div>
                        <h5 className='font-medium text-gray-400  mb-2 capitalize'>support</h5>
                        <ul>
                            <li className='capitalize py-2 text-sm  ' >pricing</li>
                            <li className='capitalize py-2 text-sm  ' >documentaion</li>
                            <li className='capitalize py-2 text-sm  ' >guides</li>
                            <li className='capitalize py-2 text-sm  ' >api status</li>
                        </ul>
                    </div>
                    <div>
                        <h5 className='font-medium text-gray-400  mb-2 capitalize'>company</h5>
                        <ul>
                            <li className='capitalize py-2 text-sm  ' >about us</li>
                            <li className='capitalize py-2 text-sm  ' >blog</li>
                            <li className='capitalize py-2 text-sm  ' >careers</li>
                            <li className='capitalize py-2 text-sm  ' >press</li>
                        </ul>
                    </div>
                    <div>
                        <h5 className='font-medium text-gray-400  mb-2 capitalize'>legal</h5>
                        <ul>
                            <li className='capitalize py-2 text-sm  ' >claim</li>
                            <li className='capitalize py-2 text-sm  ' >privacy</li>
                            <li className='capitalize py-2 text-sm  ' >terms</li>
                        </ul>
                    </div>
                </div>
            </div>

            <div className='mx-auto text-center mt-[-2rem] py-3 '>
                <p className='capitalize'>Powerd by <span className='uppercase'>Mcg</span></p>
            </div>
        </div>
    )
}
